### ISSUE TITLE
pod "Ipify" not updated to latest version

### ISSUE THREAD

**Issue by dbuskariol** [vincent-peng/swift-ipify#8]
Adding `pod "Ipify"` to my Podfile pulls Ipify (2.0.0) instead of Ipify (2.1.0) causing the following error:

```
[!] The platform of the target `ProjectName` (macOS 10.13) is not compatible with `Ipify (2.0.0)`, which does not support `osx`.
```

**Comment by vincent-peng** [comment]
If you are using CocoaPods please run `pod repo update` and try again. 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dbuskariol** [comment]
Ahh thanks @vincent-peng 👍
